spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library_project?useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
    open-in-view: off

  application:
    name: LibraryManagement

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:/D:/dev-spring/LibraryManagement/uploads/

  mail:
    host: smtp.gmail.com
    port: 587
    username: ductinnguyen251
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

api:
  prefix: api/v1

jwt:
  expiration: 604800 # 1 week
  secret-key: Pu4XEgOUeq7YxMkj0isj/2bwxGXo3Gjw3+8R7I8I7vj5UjQimKolYFRvEhwpKkD9